version: '3'
services:
  pypi:
    image: codermattie/pypi:8
    container_name: pypi-server
    ports:
      - 8080:8080
    volumes:
      - packages:/home/packages
      - ./myfile.txt:/path/in/container/myfile.txt # this is a bind, changes in container reflected in host
volumes:
  packages:
